In [20]:
import pandas as pd
import numpy as np
from copy import deepcopy

# Dashboard

In [6]:
dashboard_id = pd.read_csv("/Users/tranxuanhuy/Documents/Viettel Digital Talent/Chatbot/Code/data/CONFIG_DASHBOARD_202309051338.csv")
# dashboard_id.drop(columns=['UPDATE_TIME', 'UPDATE_USER', 'DESCRIPTION', 'STATUS'], inplace=True)
# dashboard_id = dashboard_id.applymap(lambda x: x.lower() if isinstance(x, str) else x)
dashboard_id['check_'] = dashboard_id['DASHBOARD_NAME'].apply(lambda x: 1 if x.find("_")>-1 else 0)
dashboard_id['check_2'] = dashboard_id.apply(lambda x: 1 if (x['check_']==1 and x['DASHBOARD_NAME'][x['DASHBOARD_NAME'].find("_")+1:]==str(x["ID"])) else 0, axis=1)
# dashboard_id = dashboard_id[dashboard_id['check_2']==0]
dashboard_id['DASHBOARD_NAME_NEW'] = dashboard_id.apply(lambda x: x['DASHBOARD_NAME'].replace("_"+str(x['ID']), "") if x['check_2']==1 else x['DASHBOARD_NAME'], axis=1)
condition = (dashboard_id['DASHBOARD_TYPE'] == 0) & (dashboard_id['MENU_ITEM_ID'].isna())
indices_to_drop = dashboard_id[condition].index
dashboard_id.drop(indices_to_drop, inplace=True)

profileid2donvi = {}
for profile_id in dashboard_id['PROFILE_ID'].unique():
    indexss = dashboard_id[(dashboard_id['PROFILE_ID']==profile_id)&(dashboard_id['DASHBOARD_TYPE']==1)].index
    if len(indexss) > 0:
        profileid2donvi[profile_id] = dashboard_id['DASHBOARD_NAME'].loc[dashboard_id[(dashboard_id['PROFILE_ID']==profile_id)&(dashboard_id['DASHBOARD_TYPE']==1)].index[0]]

profileid2donvinew = {}
for profile_id in dashboard_id['PROFILE_ID'].unique():
    indexss = dashboard_id[(dashboard_id['PROFILE_ID']==profile_id)&(dashboard_id['DASHBOARD_TYPE']==1)].index
    if len(indexss) > 0:
        profileid2donvinew[profile_id] = dashboard_id['DASHBOARD_NAME_NEW'].loc[dashboard_id[(dashboard_id['PROFILE_ID']==profile_id)&(dashboard_id['DASHBOARD_TYPE']==1)].index[0]]


dashboard_id['donvi'] = dashboard_id['PROFILE_ID'].apply(lambda x: profileid2donvi[x] if x in profileid2donvi.keys() else float('NaN'))
dashboard_id['donvinew'] = dashboard_id['PROFILE_ID'].apply(lambda x: profileid2donvinew[x] if x in profileid2donvi.keys() else float('NaN'))
dashboard_id

,ID,DASHBOARD_NAME,DASHBOARD_TYPE,ORDER_INDEX,PROFILE_ID,MENU_ITEM_ID,STATUS,DESCRIPTION,UPDATE_TIME,UPDATE_USER,check_,check_2,DASHBOARD_NAME_NEW,donvi,donvinew
0,3581,Doanh thu dịch vụ nhóm VTT,0,NaN,2028,2773.0,1,NaN,2021-10-14 13:54:49.000,170635,0,0,Doanh thu dịch vụ nhóm VTT,Hải Phòng,Hải Phòng
1,3582,Doanh thu dịch vụ nhóm VDS,0,NaN,2028,2778.0,1,NaN,2021-10-14 13:52:28.000,170635,0,0,Doanh thu dịch vụ nhóm VDS,Hải Phòng,Hải Phòng
2,3517,Doanh thu dịch vụ SME,0,NaN,2023,2721.0,1,NaN,2021-10-14 11:31:27.000,170635,0,0,Doanh thu dịch vụ SME,Hưng Yên,Hưng Yên
3,3518,Doanh thu dịch vụ di động,0,NaN,2023,2717.0,1,NaN,2022-07-11 17:48:45.000,269413,0,0,Doanh thu dịch vụ di động,Hưng Yên,Hưng Yên
4,3519,Doanh thu dịch vụ nhóm VTS,0,NaN,2023,2722.0,1,NaN,2021-10-14 11:30:55.000,170635,0,0,Doanh thu dịch vụ nhóm VTS,Hưng Yên,Hưng Yên
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3889,10765,Tổng doanh thu (trừ hubbing)_10765,0,NaN,3941,2422.0,1,NaN,2023-07-21 10:27:04.000,269413,1,1,Tổng doanh thu (trừ hubbing),VTS_10763,VTS
3890,10766,Tổng doanh thu tài chính_10766,0,NaN,3941,2424.0,1,NaN,2023-07-21 10:27:04.000,269413,1,1,Tổng doanh thu tài chính,VTS_10763,VTS
3891,10767,Doanh thu bán hàng giải pháp CNTT_10767,0,NaN,3941,2453.0,1,NaN,2023-07-21 10:27:04.000,269413,1,1,Doanh thu bán hàng giải pháp CNTT,VTS_10763,VTS
3892,10768,Doanh thu bán hàng y tế_10768,0,NaN,3941,2450.0,1,NaN,2023-07-21 10:27:04.000,269413,1,1,Doanh thu bán hàng y tế,VTS_10763,VTS
3893,10815,VTS,1,NaN,1959,NaN,1,NaN,2023-08-18 16:35:27.000,269413,0,0,VTS,VTS,VTS

In [7]:
# List donvi
dashboard_id['donvi'].unique()

array(['Hải Phòng', 'Hưng Yên', 'VTZ', 'MOV', 'VTPost', 'VCS', 'VTS',
       'Thanh Hoá', 'Thừa Thiên Huế', 'Hà Giang', 'Hà Nam', 'Hà Tĩnh',
       'Bắc Giang', 'VDTC', 'VTP', 'VCM', 'XMCP', 'IDC', 'An Giang',
       'Hậu Giang', 'Đồng Tháp', 'Phú Yên', 'Gia Lai', 'Hải Dương',
       'Đồng Nai', 'VBD', 'VTX', 'CÔNG TY MẸ', 'NCM', 'VDS', 'VTL', 'VCC',
       'TVTK', 'VTM', 'M3', 'M1', 'VHT', 'VTT', 'VTC', 'STL', 'NAT',
       'MYN', 'VTCC', 'Quảng Trị', 'Quảng Nam', 'Đà Nẵng', 'VTE',
       'TẬP ĐOÀN', 'KHỐI VTTN', 'KHỐI VTNN', 'Tập Đoàn', 'VTG', 'VTNet',
       nan, 'VTSport', 'BƯU CHÍNH', 'Bắc Ninh', 'Hồ Chí Minh',
       'Bà Rịa Vũng Tàu', 'Vĩnh Phúc', 'Bình Dương', 'Trà Vinh',
       'Bạc Liêu', 'Tuyên Quang', 'Thái Nguyên', 'Tiền Giang',
       'Thái Bình', 'Sóc Trăng', 'Sơn La', 'Cao bằng', 'Quảng Ngãi',
       'Cần Thơ', 'Quảng Ninh', 'Điện Biên', 'Quảng Bình', 'Ninh Thuận',
       'Nam Định', 'Ninh Bình', 'Lạng Sơn', 'Lâm Đồng', 'Hòa Bình',
       'Long An', 'Kon Tum', 'Kiên Giang', 'Yên Bái', 'Vĩnh Long',
       'Tây Ninh', 'Bình Phước', 'Bến Tre', 'Cà Mau', 'Nghệ An',
       'Khánh Hoà', 'THI PHẦN', 'Đắc Lắc', 'Ban CNTT', 'Bến tre',
       'Bình Định', 'Bắc Kạn', 'Cao Bằng', 'NCSX', 'VTT_8156', 'VTN',
       'VTA', 'VTAca', 'BDS', 'Đắc Nông', 'Lào Cai', 'Hà Nội', 'Phú Thọ',
       'VTB', 'Khối tỉnh/TP', 'Bình Thuận', 'Lai Châu', 'MẶC ĐỊNH', 'VTK',
       'XNK', 'VMC', 'TƯ VẤN THIẾT KẾ',
       'Kết quả sản xuất kinh doanh_2261', 'CÔNG TRÌNH',
       'Dashoard Văn phòng tập đoàn', 'MEDIA',
       'KHỐI NC VÀ SX THIẾT BỊ CNC', 'KHỐI CNTT',
       'KHỐI THƯƠNG MẠI VÀ LOGISTICS', 'ĐƠN VỊ KHÁC',
       'Kết quả sản xuất kinh doanh', 'Tổng doanh thu', 'XI MĂNG CẨM PHẢ',
       'QUẢN LÝ TÀI SẢN', 'KHỐI XÂY LẮP', 'Dashboard ANM',
       'Dashboard KGM', 'Dashboard XNK', 'TẬP ĐOÀN_2347',
       'Dashboard Media', 'Dashboard M1', 'Dashboard VHT',
       'Dashboard VTX', 'Dashboard Xi măng cẩm phả',
       'Dashboard Quản lý tài sản', 'Dashboard Khối CNTT',
       'Dashboard Khối Xây lắp', 'CTM', 'Tập Đoàn_9986', 'MOV_10142',
       'VTAca_10337', 'Tập đoàn', 'VTPost_9840', 'Hà Nội_10385',
       'Tập Đoàn_10186', 'Tập Đoàn_10006', 'STL_9954', 'Tập Đoàn_9926',
       'VTAca_10337_10357', 'Q.Ba Đình', 'VTT_10996', 'Hà Nội_10695',
       'Tập đoàn_10935', 'VTS_10763'], dtype=object)

In [8]:
# List donvinew
dashboard_id['donvinew'].unique()

array(['Hải Phòng', 'Hưng Yên', 'VTZ', 'MOV', 'VTPost', 'VCS', 'VTS',
       'Thanh Hoá', 'Thừa Thiên Huế', 'Hà Giang', 'Hà Nam', 'Hà Tĩnh',
       'Bắc Giang', 'VDTC', 'VTP', 'VCM', 'XMCP', 'IDC', 'An Giang',
       'Hậu Giang', 'Đồng Tháp', 'Phú Yên', 'Gia Lai', 'Hải Dương',
       'Đồng Nai', 'VBD', 'VTX', 'CÔNG TY MẸ', 'NCM', 'VDS', 'VTL', 'VCC',
       'TVTK', 'VTM', 'M3', 'M1', 'VHT', 'VTT', 'VTC', 'STL', 'NAT',
       'MYN', 'VTCC', 'Quảng Trị', 'Quảng Nam', 'Đà Nẵng', 'VTE',
       'TẬP ĐOÀN', 'KHỐI VTTN', 'KHỐI VTNN', 'Tập Đoàn', 'VTG', 'VTNet',
       nan, 'VTSport', 'BƯU CHÍNH', 'Bắc Ninh', 'Hồ Chí Minh',
       'Bà Rịa Vũng Tàu', 'Vĩnh Phúc', 'Bình Dương', 'Trà Vinh',
       'Bạc Liêu', 'Tuyên Quang', 'Thái Nguyên', 'Tiền Giang',
       'Thái Bình', 'Sóc Trăng', 'Sơn La', 'Cao bằng', 'Quảng Ngãi',
       'Cần Thơ', 'Quảng Ninh', 'Điện Biên', 'Quảng Bình', 'Ninh Thuận',
       'Nam Định', 'Ninh Bình', 'Lạng Sơn', 'Lâm Đồng', 'Hòa Bình',
       'Long An', 'Kon Tum', 'Kiên Giang', 'Yên Bái', 'Vĩnh Long',
       'Tây Ninh', 'Bình Phước', 'Bến Tre', 'Cà Mau', 'Nghệ An',
       'Khánh Hoà', 'THI PHẦN', 'Đắc Lắc', 'Ban CNTT', 'Bến tre',
       'Bình Định', 'Bắc Kạn', 'Cao Bằng', 'NCSX', 'VTN', 'VTA', 'VTAca',
       'BDS', 'Đắc Nông', 'Lào Cai', 'Hà Nội', 'Phú Thọ', 'VTB',
       'Khối tỉnh/TP', 'Bình Thuận', 'Lai Châu', 'MẶC ĐỊNH', 'VTK', 'XNK',
       'VMC', 'TƯ VẤN THIẾT KẾ', 'Kết quả sản xuất kinh doanh',
       'CÔNG TRÌNH', 'Dashoard Văn phòng tập đoàn', 'MEDIA',
       'KHỐI NC VÀ SX THIẾT BỊ CNC', 'KHỐI CNTT',
       'KHỐI THƯƠNG MẠI VÀ LOGISTICS', 'ĐƠN VỊ KHÁC', 'Tổng doanh thu',
       'XI MĂNG CẨM PHẢ', 'QUẢN LÝ TÀI SẢN', 'KHỐI XÂY LẮP',
       'Dashboard ANM', 'Dashboard KGM', 'Dashboard XNK',
       'Dashboard Media', 'Dashboard M1', 'Dashboard VHT',
       'Dashboard VTX', 'Dashboard Xi măng cẩm phả',
       'Dashboard Quản lý tài sản', 'Dashboard Khối CNTT',
       'Dashboard Khối Xây lắp', 'CTM', 'Tập đoàn', 'VTAca_10337_10357',
       'Q.Ba Đình'], dtype=object)

In [43]:
# API sẽ test
i = ['VTS', 'VTS_10763', 'VTAca_10337_10357', 'Cà Mau'][-1]
dashboard_id[dashboard_id['donvi']==i]

,ID,DASHBOARD_NAME,DASHBOARD_TYPE,ORDER_INDEX,PROFILE_ID,MENU_ITEM_ID,STATUS,DESCRIPTION,UPDATE_TIME,UPDATE_USER,check_,check_2,DASHBOARD_NAME_NEW,donvi,donvinew
771,6529,Cà Mau,1,NaN,2094,NaN,1,NaN,2022-03-16 13:54:50.000,170635,0,0,Cà Mau,Cà Mau,Cà Mau
1285,6355,Cà Mau,1,NaN,2093,NaN,1,NaN,2022-03-14 15:03:49.000,slgb_admin_bi,0,0,Cà Mau,Cà Mau,Cà Mau
2168,4301,Doanh thu dịch vụ SME,0,NaN,2094,3502.0,1,NaN,2021-10-17 13:31:53.000,170635,0,0,Doanh thu dịch vụ SME,Cà Mau,Cà Mau
2169,4302,Doanh thu dịch vụ di động,0,NaN,2094,3498.0,1,NaN,2022-07-11 17:51:50.000,slgb_admin_bi,0,0,Doanh thu dịch vụ di động,Cà Mau,Cà Mau
2170,4303,Doanh thu dịch vụ nhóm VTS,0,NaN,2094,3503.0,1,NaN,2021-10-17 13:29:31.000,170635,0,0,Doanh thu dịch vụ nhóm VTS,Cà Mau,Cà Mau
2171,4304,Thuê bao FTTH,0,NaN,2094,3494.0,1,NaN,2021-10-17 13:28:30.000,170635,0,0,Thuê bao FTTH,Cà Mau,Cà Mau
2172,4305,Thuê bao di động phát triển thực,0,NaN,2094,3497.0,1,NaN,2022-01-10 09:40:48.000,170635,0,0,Thuê bao di động phát triển thực,Cà Mau,Cà Mau
2173,4306,Thuê bao 4G phát triển thực,0,NaN,2094,3496.0,1,NaN,2021-10-17 13:25:16.000,170635,0,0,Thuê bao 4G phát triển thực,Cà Mau,Cà Mau
2174,4307,Tổng doanh thu dịch vụ,0,NaN,2094,3500.0,1,NaN,2022-01-20 16:14:39.000,170635,0,0,Tổng doanh thu dịch vụ,Cà Mau,Cà Mau
2175,4308,Thuê bao register,0,NaN,2094,3495.0,1,NaN,2021-11-04 16:52:22.000,170635,0,0,Thuê bao register,Cà Mau,Cà Mau
2176,4309,Doanh thu dịch vụ cố định băng rộng,0,NaN,2094,3501.0,1,NaN,2021-10-17 13:20:55.000,170635,0,0,Doanh thu dịch vụ cố định băng rộng,Cà Mau,Cà Mau
2177,4310,Doanh thu dịch vụ nhóm VTT,0,NaN,2094,3499.0,1,NaN,2021-10-17 13:19:42.000,170635,0,0,Doanh thu dịch vụ nhóm VTT,Cà Mau,Cà Mau
2178,4311,Doanh thu dịch vụ nhóm VDS,0,NaN,2094,3504.0,1,NaN,2021-10-17 13:18:06.000,170635,0,0,Doanh thu dịch vụ nhóm VDS,Cà Mau,Cà Mau
2330,4290,Doanh thu dịch vụ SME,0,NaN,2093,3491.0,1,NaN,2021-10-17 13:16:53.000,170635,0,0,Doanh thu dịch vụ SME,Cà Mau,Cà Mau
2342,4291,Doanh thu dịch vụ di động,0,NaN,2093,3487.0,1,NaN,2021-10-17 13:15:47.000,170635,0,0,Doanh thu dịch vụ di động,Cà Mau,Cà Mau
2343,4292,Doanh thu dịch vụ nhóm VTS,0,NaN,2093,3492.0,1,NaN,2021-10-17 13:14:35.000,170635,0,0,Doanh thu dịch vụ nhóm VTS,Cà Mau,Cà Mau
2344,4293,Thuê bao FTTH,0,NaN,2093,3484.0,1,NaN,2021-10-17 13:13:23.000,170635,0,0,Thuê bao FTTH,Cà Mau,Cà Mau
2345,4294,Thuê bao di động phát triển thực,0,NaN,2093,3486.0,1,NaN,2022-01-10 09:40:15.000,170635,0,0,Thuê bao di động phát triển thực,Cà Mau,Cà Mau
2346,4295,Thuê bao 4G phát triển thực,0,NaN,2093,3485.0,1,NaN,2021-10-17 13:10:49.000,170635,0,0,Thuê bao 4G phát triển thực,Cà Mau,Cà Mau
2347,4296,Tổng doanh thu dịch vụ,0,NaN,2093,3489.0,1,NaN,2021-10-17 13:37:32.000,170635,0,0,Tổng doanh thu dịch vụ,Cà Mau,Cà Mau
2348,4297,Thuê bao register,0,NaN,2093,3483.0,1,NaN,2021-11-04 16:39:39.000,170635,0,0,Thuê bao register,Cà Mau,Cà Mau
2349,4298,Doanh thu dịch vụ cố định băng rộng,0,NaN,2093,3490.0,1,NaN,2022-03-22 14:13:49.000,170635,0,0,Doanh thu dịch vụ cố định băng rộng,Cà Mau,Cà Mau
2350,4299,Doanh thu dịch vụ nhóm VTT,0,NaN,2093,3488.0,1,NaN,2021-10-17 13:05:55.000,170635,0,0,Doanh thu dịch vụ nhóm VTT,Cà Mau,Cà Mau
2351,4300,Doanh thu dịch vụ nhóm VDS,0,NaN,2093,3493.0,1,NaN,2021-10-17 13:04:10.000,170635,0,0,Doanh thu dịch vụ nhóm VDS,Cà Mau,Cà Mau

In [47]:
# Dashboard param tree
dashboard_param = pd.read_csv("/Users/tranxuanhuy/Documents/Viettel Digital Talent/Chatbot/Code/data/DASHBOARD_PARAM_TREE_202307280939.csv")
dashboard_param.drop(columns=["PARAM_ORDER_SMS", "DEPT_ORDER", "SUB_CODE", "IMAGE",
                              "STATUS", "TYPE_PARAM", "GROUP_TYPE",
                              "START_TIME", "END_TIME",
                              "MODIFIED_DATE"], inplace=True)
dashboard_param

,CODE,NAME,PARENT,PARAM_ORDER,LEVEL_NODE,ID,DEPT_ID,PARENT_DEPT_ID,STANDARD_NAME
0,VTG_METFONE,"Metfone_CT Viettel Cambodia Pte., Ltd",VTG,0,11.0,100676,308469,256.0,NaN
1,TTTT,VTSport_TT Thể thao Viettel,CPLTM,5,NaN,100698,2108,308480.0,NaN
2,HVT,VTAca_Học viện Viettel,CPLTM,4,NaN,100699,305965,308480.0,NaN
3,VTH,TT KD Sản phẩm công nghệ cao Viettel,SXTBCNC_HHL,1,NaN,100724,7920,308482.0,NaN
4,VTEK,TT Nghiên cứu công nghệ mạng Viettel,SXTBCNC_HHL,0,NaN,100725,1709,308482.0,NaN
...,...,...,...,...,...,...,...,...,...
838,Y029006,H.Trấn Yên,Y029,4,NaN,101613,949,314.0,H.Trấn Yên
839,Y029008,H.Văn Chấn,Y029,5,NaN,101614,951,314.0,H.Văn Chấn
840,Y029004,H.Văn Yên,Y029,6,NaN,101615,947,314.0,H.Văn Yên
841,Y029007,H.Yên Bình,Y029,7,NaN,101616,950,314.0,H.Yên Bình
842,Y029002,TX.Nghĩa Lộ,Y029,8,NaN,101617,945,314.0,TX.Nghĩa Lộ

In [57]:
dashboard_param['STANDARD_NAME'].unique()

array([nan, 'NBH', 'NTN', 'PTO', 'PYN', 'QBH', 'QNM', 'QNI', 'QNH', 'QTI',
       'STG', 'SLA', 'TNH', 'TBH', 'TNN', 'THA', 'HUE', 'TGG', 'HCM',
       'TVH', 'TQG', 'VLG', 'VPC', 'YBI', 'Bitel', 'GPCNDV', 'GPCNDV_HHL',
       'SXTBCNC', 'CPLTM', 'KTM', 'LCU', 'LDG', 'LSN', 'LCI', 'LAN',
       'NDH', 'NAN', 'VT', 'VTG', 'VTK', 'HNI', 'AGG', 'VTU', 'BGG',
       'BKN', 'BLU', 'BNH', 'BTE', 'BDH', 'BDG', 'BPC', 'BTN', 'CMU',
       'CTO', 'CBG', 'DNG', 'DLK', 'DCN', 'DBN', 'DNI', 'DTP', 'GLI',
       'HGG', 'HNM', 'HTH', 'HDG', 'HPG', 'HUG', 'HBH', 'HYN', 'KHA',
       'KGG', 'H.Việt Yên', 'H.Yên Dũng', 'H.Yên Thế', 'TP.Bắc Kạn',
       'H.Ba Bể', 'H.Bạch Thông', 'H.Chợ Đồn', 'H.Chợ Mới', 'H.Na Rì',
       'H.Ngân Sơn', 'H.Pắc Nặm', 'TP.Bạc Liêu', 'H.Đông Hải',
       'H.Hòa Bình', 'H.Hồng Dân', 'H.Phước Long', 'H.Vĩnh Lợi',
       'TX.Giá Rai', 'TP.Bắc Ninh', 'TP.Từ Sơn', 'H.Gia Bình',
       'H.Lương Tài', 'H.Quế Võ', 'H.Thuận Thành', 'H.Tiên Du',
       'H.Yên Phong', 'TP.Đồng Xoài', 'H.Bù Đăng', 'H.Bù Đốp',
       'H.Bù Gia Mập', 'H.Đồng Phú', 'H.Hớn Quản', 'H.Lộc Ninh',
       'H.Phú Riềng', 'TX.Bình Long', 'TX.Chơn Thành', 'TX.Phước Long',
       'TP.Bến Tre', 'H.Ba Tri', 'H.Bình Đại', 'H.Châu Thành',
       'H.Chợ Lách', 'H.Giồng Trôm', 'H.Mỏ Cày Bắc', 'H.Mỏ Cày Nam',
       'H.Thạnh Phú', 'TP.Phan Thiết', 'H.Bắc Bình', 'H.Đức Linh',
       'H.Hàm Tân', 'H.Hàm Thuận Bắc', 'H.Hàm Thuận Nam', 'H.Phú Quý',
       'H.Tánh Linh', 'H.Tuy Phong', 'TX.La Gi', 'TP.Cao Bằng',
       'H.Bảo Lạc', 'H.Bảo Lâm', 'H.Hạ Lang', 'H.Hà Quảng', 'H.Hòa An',
       'H.Nguyên Bình', 'H.Quảng Hoà', 'H.Thạch An', 'H.Trùng Khánh',
       'TP.Cà Mau', 'H.Cái Nước', 'H.Đầm Dơi', 'H.Năm Căn', 'H.Ngọc Hiển',
       'H.Phú Tân', 'H.Thới Bình', 'H.Trần Văn Thời', 'H.U Minh',
       'Q.Bình Thủy', 'Q.Cái Răng', 'Q.Ninh Kiều', 'Q.Ô Môn', 'H.Cờ Đỏ',
       'H.Phong Điền', 'H.Thới Lai', 'H.Thốt Nốt', 'H.Vĩnh Thạnh',
       'TP.Điện Biên Phủ', 'H.Điện Biên', 'H.Điện Biên Đông',
       'H.Mường ảng', 'H.Mường Chà', 'H.Mường Nhé', 'H.Nậm Pồ',
       'H.Tủa Chùa', 'H.Tuần Giáo', 'TX.Mường Lay', 'TP.Gia Nghĩa',
       'H.Cư Jút', 'H.Đắk Glong', 'H.Đắk Mil', 'H.Đắk Nông', 'H.Đắk RLấp',
       'H.Đắk Song', 'H.Krông Nô', 'H.Tuy Đức', 'TP.Buôn Ma Thuột',
       'H.Buôn Đôn', 'H.Cư Kuin', 'H.Cư Mgar', 'H.Ea Hleo', 'H.Ea Kar',
       'H.Ea Súp', 'H.Krông A Na', 'H.Krông Bông', 'H.Krông Búk',
       'H.Krông Năng', 'H.Krông Pắk', 'H.Lắk', 'H.MĐrăk', 'TX.Buôn Hồ',
       'Q.Cẩm Lệ', 'Q.Hải Châu', 'Q.Liên Chiểu', 'Q.Ngũ Hành Sơn',
       'Q.Sơn Trà', 'Q.Thanh Khê', 'H.Hòa Vang', 'TP.Biên Hòa',
       'H.Cẩm Mỹ', 'H.Định Quán', 'H.TP.Long Khánh', 'H.Long Thành',
       'H.Nhơn Trạch', 'H.Tân Phú', 'H.Thống Nhất', 'H.Trảng Bom',
       'H.Vĩnh Cửu', 'H.Xuân Lộc', 'TP.Cao Lãnh', 'TP.Sa Đéc',
       'H.Cao Lãnh', 'H.Hồng Ngự', 'H.Lai Vung', 'H.Lấp Vò', 'H.Tam Nông',
       'H.Tân Hồng', 'H.Thanh Bình', 'H.Tháp Mười', 'TX.Hồng Ngự',
       'TP.Pleiku', 'H.Chư Păh', 'H.Chư Prông', 'H.Chư Pưh', 'H.Chư Sê',
       'H.Đắc Pơ', 'H.Đăk Đoa', 'H.Đức Cơ', 'H.Ia Grai', 'H.Ia Pa',
       'H.Kbang', 'H.Kông Chro', 'H.Krông Pa', 'H.Mang Yang',
       'H.Phú Thiện', 'TX.An Khê', 'TX.Ayun Pa', 'TP.Hòa Bình',
       'H.Cao Phong', 'H.Đà Bắc', 'H.Kim Bôi', 'H.Kỳ Sơn', 'H.Lạc Sơn',
       'H.Lạc Thủy', 'H.Lương Sơn', 'H.Mai Châu', 'H.Tân Lạc',
       'H.Yên Thủy', 'TP.Hải Dương', 'H.Bình Giang', 'H.Cẩm Giàng',
       'H.Gia Lộc', 'H.Kim Thành', 'H.Kinh Môn', 'H.Nam Sách',
       'H.Ninh Giang', 'H.Thanh Hà', 'H.Thanh Miện', 'H.Tứ Kỳ',
       'TX.Chí Linh', 'TP.Hà Giang', 'H.Bắc Mê', 'H.Bắc Quang',
       'H.Đồng Văn', 'H.Hoàng Su Phì', 'H.Mèo Vạc', 'H.Quản Bạ',
       'H.Quang Bình', 'H.Vị Xuyên', 'H.Xín Mần', 'H.Yên Minh',
       'TP.Phủ Lý', 'H.Bình Lục', 'H.Duy Tiên', 'H.Kim Bảng', 'H.Lý Nhân',
       'H.Thanh Liêm', 'Q.Đồ Sơn', 'Q.Dương Kinh', 'Q.Hải An',
       'Q.Hồng Bàng', 'Q.Kiến An', 'Q.Lê Chân', 'Q.Ngô Quyền',
       'H.An Dương', 'H.An Lão', 'H.Bạch Long Vĩ', 'H.Cát Hải',
       'H.Kiến Thụy', 'H.Thủy Nguyên', 'H.Tiên Lãng', 'H.Vĩnh Bảo',
       'TP.Hà Tĩnh', 'H.Cẩm Xuyên', 'H.Can Lộc', 'H.Đức Thọ',
       'H.Hương Khê', 'H.Hương Sơn', 'H.Kỳ Anh', 'H.Lộc Hà',
       'H.Nghi Xuân', 'H.Thạch Hà', 'H.Vũ Quang', 'TX.Hồng Lĩnh',
       'TX.Kỳ Anh', 'TP.Huế', 'H.A Lưới', 'H.Nam Đông', 'H.Phú Lộc',
       'H.Phú Vang', 'H.Quảng Điền', 'TX.Hương Thủy', 'TX.Hương Trà',
       'TP.Ngã Bảy', 'TP.Vị Thanh', 'H.Châu Thành A', 'H.Long Mỹ',
       'H.Phụng Hiệp', 'H.Vị Thủy', 'TX.Long Mỹ', 'TP.Hưng Yên',
       'H.Ân Thi', 'H.Khoái Châu', 'H.Kim Động', 'H.Mỹ Hào', 'H.Phù Cừ',
       'H.Tiên Lữ', 'H.Văn Giang', 'H.Văn Lâm', 'H.Yên Mỹ', 'TP.Rạch Giá',
       'H.An Biên', 'H.An Minh', 'H.Giang Thành', 'H.Giồng Riềng',
       'H.Gò Quao', 'Q.Ba Đình', 'Q.Bắc Từ Liêm', 'Q.Cầu Giấy',
       'Q.Đống Đa', 'Q.Hà Đông', 'Q.Hai Bà Trưng', 'Q.Hoàn Kiếm',
       'Q.Hoàng Mai', 'Q.Long Biên', 'Q.Nam Từ Liêm', 'Q.Tây Hồ',
       'Q.Thanh Xuân', 'H.Ba Vì', 'H.Chương Mỹ', 'H.Đan Phượng',
       'H.Đông Anh', 'H.Gia Lâm', 'H.Hoài Đức', 'H.Mê Linh', 'H.Mỹ Đức',
       'H.Phú Xuyên', 'H.Phúc Thọ', 'H.Quốc Oai', 'H.Sóc Sơn',
       'H.Thạch Thất', 'H.Thanh Oai', 'H.Thanh Trì', 'H.Thường Tín',
       'H.Ứng Hòa', 'TX.Sơn Tây', 'Q.1', 'Q.2', 'Q.3', 'Q.4', 'Q.5',
       'Q.6', 'Q.7', 'Q.8', 'Q.9', 'Q.10', 'Q.11', 'Q.12', 'Q.Bình Tân',
       'Q.Bình Thạnh', 'Q.Gò Vấp', 'Q.Phú Nhuận', 'Q.Tân Bình',
       'Q.Tân Phú', 'Q.Thủ Đức', 'H.Bình Chánh', 'H.Cần Giờ', 'H.Củ Chi',
       'H.Hóc Môn', 'H.Nhà Bè', 'TP.Châu Đốc', 'TP.Long Xuyên',
       'H.An Phú', 'H.Châu Phú', 'H.Thoại Sơn', 'H.Tịnh Biên',
       'H.Tri Tôn', 'TX.Tân Châu', 'TP.Dĩ An', 'TP.Tân Uyên',
       'TP.Thủ Dầu Một', 'TP.Thuận An', 'H.Bắc Tân Uyên', 'H.Bàu Bàng',
       'H.Dầu Tiếng', 'H.Phú Giáo', 'TX.Bến Cát', 'TP.Quy Nhơn',
       'H.Hoài Ân', 'H.Hoài Nhơn', 'H.Phù Cát', 'H.Phù Mỹ', 'H.Tây Sơn',
       'H.Tuy Phước', 'H.Vân Canh', 'TX.An Nhơn', 'TP.Bắc Giang',
       'H.Hiệp Hòa', 'H.Lạng Giang', 'H.Lục Nam', 'H.Lục Ngạn',
       'H.Sơn Động', 'H.Tân Yên', 'H.Hòn Đất', 'H.Kiên Hải',
       'H.Kiên Lương', 'H.Phú Quốc', 'H.Tân Hiệp', 'H.U Minh Thượng',
       'H.Vĩnh Thuận', 'TX.Hà Tiên', 'TP.Cam Ranh', 'TP.Nha Trang',
       'H.Cam Lâm', 'H.Diên Khánh', 'H.Khánh Sơn', 'H.Khánh Vĩnh',
       'H.Trường Sa', 'H.Vạn Ninh', 'TX.Ninh Hòa', 'TP.Kon Tum',
       'H.Đắk Glei', 'H.Đắk Hà', 'H.Đắk Tô', 'H.Kon Plông', 'H.Kon Rẫy',
       'H.la H Drai', 'H.Ngọc Hồi', 'H.Sa Thầy', 'H.Tu mơ rông',
       'TP.Tân An', 'H.Bến Lức', 'H.Cần Đước', 'H.Cần Giuộc', 'H.Đức Hòa',
       'H.Đức Huệ', 'H.Mộc Hóa', 'H.Tân Hưng', 'H.Tân Thạnh', 'H.Tân Trụ',
       'H.Thạnh Hóa', 'H.Thủ Thừa', 'H.Vĩnh Hưng', 'TX.Kiến Tường',
       'TP.Lào Cai', 'H.Bắc Hà', 'H.Bảo Thắng', 'H.Bảo Yên', 'H.Bát Xát',
       'H.Mường Khương', 'H.Si Ma Cai', 'H.Văn Bàn', 'TX.Sa Pa',
       'TP.Lai Châu', 'H.Mường Tè', 'H.Nậm Nhùn', 'H.Phong Thổ',
       'H.Sìn Hồ', 'H.Tam Đường', 'H.Tân Uyên', 'H.Than Uyên',
       'TP.Bảo Lộc', 'TP.Đà Lạt', 'H.Cát Tiên', 'H.Đạ Huoai', 'H.Đạ Tẻh',
       'H.Đam Rông', 'H.Di Linh', 'H.Đơn Dương', 'H.Đức Trọng',
       'H.Lạc Dương', 'H.Lâm Hà', 'TP.Lạng Sơn', 'H.Bắc Sơn',
       'H.Bình Gia', 'H.Cao Lộc', 'H.Chi Lăng', 'H.Đình Lập',
       'H.Hữu Lũng', 'H.Lộc Bình', 'H.Tràng Định', 'H.Văn Lãng',
       'H.Văn Quan', 'TP.Vinh', 'H.Anh Sơn', 'H.Con Cuông', 'H.Diễn Châu',
       'H.Đô Lương', 'H.Hưng Nguyên', 'H.Nam Đàn', 'H.Nghi Lộc',
       'H.Nghĩa Đàn', 'H.Quế Phong', 'H.Quỳ Châu', 'H.Quỳ Hợp',
       'H.Quỳnh Lưu', 'H.Tân Kỳ', 'H.Thái Hòa', 'H.Thanh Chương',
       'H.Tương Dương', 'H.Yên Thành', 'TX.Cửa Lò', 'TX.Hoàng Mai',
       'TP.Ninh Bình', 'TP.Tam Điệp', 'H.Gia Viễn', 'H.Hoa Lư',
       'H.Kim Sơn', 'H.Nho Quan', 'H.Yên Khánh', 'H.Yên Mô',
       'TP.Nam Định', 'H.Giao Thủy', 'H.Hải Hậu', 'H.Mỹ Lộc',
       'H.Nam Trực', 'H.Nghĩa Hưng', 'H.Trực Ninh', 'H.Vụ Bản',
       'H.Xuân Trường', 'H.Ý Yên', 'TP.Phan Rang -Tháp Chàm', 'H.Bác ái',
       'H.Ninh Hải', 'H.Ninh Phước', 'H.Ninh Sơn', 'H.Thuận Bắc',
       'H.Thuận Nam', 'TP.Việt Trì', 'H.Cẩm Khê', 'H.Đoan Hùng',
       'H.Hạ Hòa', 'H.Lâm Thao', 'H.Phù Ninh', 'H.Tân Sơn', 'H.Thanh Ba',
       'H.Thanh Sơn', 'H.Thanh Thủy', 'H.Yên Lập', 'TX.Phú Thọ',
       'TP.Tuy Hòa', 'H.Đồng Xuân', 'H.Phú Hòa', 'H.Sơn Hòa',
       'H.Sông Hinh', 'H.Tây Hòa', 'H.Tuy An', 'TX.Đông Hòa',
       'TX.Sông Cầu', 'TP.Đồng Hới', 'H.Bố Trạch', 'H.Lệ Thủy',
       'H.Minh Hóa', 'H.Quảng Ninh', 'H.Quảng Trạch', 'H.Tuyên Hóa',
       'TX.Ba Đồn', 'TP.Cẩm Phả', 'TP.Hạ Long', 'TP.Móng Cái',
       'TP.Uông Bí', 'H.Ba Chẽ', 'H.Bình Liêu', 'H.Cô Tô', 'H.Đầm Hà',
       'H.Hải Hà', 'H.Hoành Bồ', 'H.Tiên Yên', 'H.Vân Đồn',
       'TX.Đông Triều', 'TX.Quảng Yên', 'TP.Quảng Ngãi', 'H.Ba Tơ',
       'H.Bình Sơn', 'H.Lý Sơn', 'H.Minh Long', 'H.Sơn Tịnh', 'H.Mộ Đức',
       'H.Nghĩa Hành', 'H.Sơn Hà', 'H.Sơn Tây', 'H.Trà Bồng',
       'H.Tư Nghĩa', 'TX.Đức Phổ', 'TP.Hội An', 'TP.Tam Kỳ',
       'H.Bắc Trà My', 'H.Đại Lộc', 'H.Đông Giang', 'H.Duy Xuyên',
       'H.Hiệp Đức', 'H.Nam Giang', 'H.Nam Trà My', 'H.Nông Sơn',
       'H.Núi Thành', 'H.Phú Ninh', 'H.Phước Sơn', 'H.Quế Sơn',
       'H.Tây Giang', 'H.Thăng Bình', 'H.Tiên Phước', 'TX.Điện Bàn',
       'TP.Đông Hà', 'H.Cam Lộ', 'H.Đa Krông', 'H.Đảo Cồn Cỏ',
       'H.Gio Linh', 'H.Hải Lăng', 'H.Hướng Hóa', 'H.Triệu Phong',
       'H.Vĩnh Linh', 'TX.Quảng Trị', 'TP.Sơn La', 'H.Bắc Yên',
       'H.Mai Sơn', 'H.Mộc Châu', 'H.Mường La', 'H.Phù Yên',
       'H.Quỳnh Nhai', 'H.Sông Mã', 'H.Sốp Cộp', 'H.Thuận Châu',
       'H.Vân Hồ', 'H.Yên Châu', 'TP.Sóc Trăng', 'H.Cù Lao Dung',
       'H.Kế Sách', 'H.Long Phú', 'H.Mỹ Tú', 'H.Mỹ Xuyên', 'H.Thạnh Trị',
       'H.Trần Đề', 'TX.Ngã Năm', 'TX.Vĩnh Châu', 'TP.Thái Bình',
       'H.Đông Hưng', 'H.Hưng Hà', 'H.Kiến Xương', 'H.Quỳnh Phụ',
       'H.Thái Thụy', 'H.Tiền Hải', 'H.Vũ Thư', 'TP.Mỹ Tho', 'H.Cái Bè',
       'H.Cai Lậy', 'H.Chợ Gạo', 'H.Gò Công Đông', 'H.Gò Công Tây',
       'H.Tân Phú Đông', 'H.Tân Phước', 'TX.Cai Lậy', 'TX.Gò Công',
       'TP.Sầm Sơn', 'TP.Thanh Hóa', 'H.Bá Thước', 'H.Cẩm Thủy',
       'H.Đông Sơn', 'H.Hà Trung', 'H.Hậu Lộc', 'H.Hoằng Hóa',
       'H.Lang Chánh', 'H.Mường Lát', 'H.Nga Sơn', 'H.Ngọc Lặc',
       'H.Như Thanh', 'H.Như Xuân', 'H.Nông Cống', 'H.Quan Hóa',
       'H.Quan Sơn', 'H.Quảng Xương', 'H.Thạch Thành', 'H.Thiệu Hóa',
       'H.Thọ Xuân', 'H.Thường Xuân', 'H.Triệu Sơn', 'H.Vĩnh Lộc',
       'H.Yên Định', 'TX.Bỉm Sơn', 'TX.Nghi Sơn', 'TP.Tây Ninh',
       'H.Bến Cầu', 'H.Dương Minh Châu', 'H.Gò Dầu', 'H.Tân Biên',
       'H.Tân Châu', 'TX.Hòa Thành', 'TX.Trảng Bàng', 'TP.Sông Công',
       'TP.Thái Nguyên', 'H.Đại Từ', 'H.Định Hóa', 'H.Đồng Hỷ',
       'H.Phú Bình', 'H.Phú Lương', 'H.Võ Nhai', 'TX.Phổ Yên',
       'TP.Tuyên Quang', 'H.Chiêm Hóa', 'H.Hàm Yên', 'H.Lâm Bình',
       'H.Na Hang', 'H.Sơn Dương', 'H.Yên Sơn', 'TP.Trà Vinh',
       'H.Càng Long', 'H.Cầu Kè', 'H.Cầu Ngang', 'H.Duyên Hải',
       'H.Tiểu Cần', 'H.Trà Cú', 'TX.Duyên Hải', 'TP.Vĩnh Long',
       'H.Bình Tân', 'H.Long Hồ', 'H.Mang Thít', 'H.Tam Bình', 'H.Trà Ôn',
       'H.Vũng Liêm', 'TX.Bình Minh', 'TP.Phúc Yên', 'TP.Vĩnh Yên',
       'H.Bình Xuyên', 'H.Lập Thạch', 'H.Sông Lô', 'H.Tam Đảo',
       'H.Tam Dương', 'H.Vĩnh Tường', 'H.Yên Lạc', 'TP.Bà Rịa',
       'TP.Vũng Tàu', 'H.Châu Đức', 'H.Côn Đảo', 'H.Đất Đỏ',
       'H.Long Điền', 'H.Xuyên Mộc', 'TX.Phú Mỹ', 'TP.Yên Bái',
       'H.Lục Yên', 'H.Mù Cang Chải', 'H.Trạm Tấu', 'H.Trấn Yên',
       'H.Văn Chấn', 'H.Văn Yên', 'H.Yên Bình', 'TX.Nghĩa Lộ'],
      dtype=object)

In [56]:
print(len(dashboard_param['PARENT'].unique()))
dashboard_param['PARENT'].unique()

74

array(['VTG', 'CPLTM', 'SXTBCNC_HHL', 'TSS', 'TD', 'VT', nan, 'GPCNDV',
       'SXTBCNC', 'GPCNDV_HHL', 'CPLTM_HHL', 'B240', 'B281', 'B781',
       'B241', 'B651', 'B075', 'B062', 'C026', 'C780', 'C710', 'D230',
       'D501', 'D500', 'D511', 'D061', 'D067', 'G059', 'H018', 'H320',
       'H019', 'N351', 'H031', 'H039', 'T054', 'H711', 'H321', 'K077',
       'H004', 'T008', 'A076', 'B650', 'B056', 'K058', 'K060', 'L072',
       'L020', 'L231', 'L063', 'L025', 'N038', 'N030', 'N350', 'N068',
       'P210', 'P057', 'Q052', 'Q033', 'Q055', 'Q510', 'Q053', 'S022',
       'S079', 'T036', 'T073', 'T037', 'T066', 'T280', 'T027', 'T074',
       'V070', 'V211', 'V064', 'Y029'], dtype=object)

In [54]:
dashboard_param[dashboard_param['PARENT']=='B240']

,CODE,NAME,PARENT,PARAM_ORDER,LEVEL_NODE,ID,DEPT_ID,PARENT_DEPT_ID,STANDARD_NAME
134,B240009,H.Việt Yên,B240,7,NaN,101001,980,293.0,H.Việt Yên
135,B240010,H.Yên Dũng,B240,8,NaN,101002,981,293.0,H.Yên Dũng
136,B240002,H.Yên Thế,B240,9,NaN,101003,963,293.0,H.Yên Thế
486,B240001,TP.Bắc Giang,B240,0,NaN,100994,962,293.0,TP.Bắc Giang
487,B240005,H.Hiệp Hòa,B240,1,NaN,100995,966,293.0,H.Hiệp Hòa
488,B240006,H.Lạng Giang,B240,2,NaN,100996,967,293.0,H.Lạng Giang
489,B240008,H.Lục Nam,B240,3,NaN,100997,979,293.0,H.Lục Nam
490,B240004,H.Lục Ngạn,B240,4,NaN,100998,965,293.0,H.Lục Ngạn
491,B240007,H.Sơn Động,B240,5,NaN,100999,968,293.0,H.Sơn Động
492,B240003,H.Tân Yên,B240,6,NaN,101000,964,293.0,H.Tân Yên

In [48]:
dashboard_param[dashboard_param['PARENT']=='Y029']

,CODE,NAME,PARENT,PARAM_ORDER,LEVEL_NODE,ID,DEPT_ID,PARENT_DEPT_ID,STANDARD_NAME
834,Y029001,TP.Yên Bái,Y029,0,NaN,101609,944,314.0,TP.Yên Bái
835,Y029003,H.Lục Yên,Y029,1,NaN,101610,946,314.0,H.Lục Yên
836,Y029005,H.Mù Cang Chải,Y029,2,NaN,101611,948,314.0,H.Mù Cang Chải
837,Y029009,H.Trạm Tấu,Y029,3,NaN,101612,952,314.0,H.Trạm Tấu
838,Y029006,H.Trấn Yên,Y029,4,NaN,101613,949,314.0,H.Trấn Yên
839,Y029008,H.Văn Chấn,Y029,5,NaN,101614,951,314.0,H.Văn Chấn
840,Y029004,H.Văn Yên,Y029,6,NaN,101615,947,314.0,H.Văn Yên
841,Y029007,H.Yên Bình,Y029,7,NaN,101616,950,314.0,H.Yên Bình
842,Y029002,TX.Nghĩa Lộ,Y029,8,NaN,101617,945,314.0,TX.Nghĩa Lộ

# Chart ID List

In [12]:
service_id_all = pd.read_csv("/Users/tranxuanhuy/Documents/Viettel Digital Talent/Chatbot/Code/data/SERVICE_ID_infor.csv")
service_id_list = list(set(service_id_all['SERVICE_ID']))
service_id_dictionary = {u: list(set(service_id_all[service_id_all['SERVICE_ID']==u]['SERVICE_NAME']))[0] for u in service_id_list}

In [17]:

chart_dept = pd.read_csv("/Users/tranxuanhuy/Documents/Viettel Digital Talent/Chatbot/Code/data/D_CHART_DEPT_SERVICE_202307280943.csv")
chart_dept.drop(columns=["GROUP_CHART"], inplace=True)
chart_dept['SERVICE_NAME'] = chart_dept['SERVICE_ID'].apply(lambda i: service_id_dictionary[i] if i in service_id_dictionary.keys() else "")
chart_dept

,ID,DEPT_CODE,SERVICE_ID,CHART_ID,TITLE_CHART,TYPE_CHART,CYCTIME,UPDATE_DATE,SERVICE_NAME
0,77254,B281,143,16558,DOANH THU DỊCH VỤ TỔNG,MINI,NGAY,2022-08-08 09:47:22.000,DOANH THU DỊCH VỤ (chi tiết)
1,77255,B281,143,16558,DOANH THU DỊCH VỤ TỔNG,TITLE_MOBILE,NGAY,2022-08-08 09:47:22.000,DOANH THU DỊCH VỤ (chi tiết)
2,77256,B281,143,16558,DOANH THU DỊCH VỤ TỔNG,CHART_RANK_2,NGAY,2022-08-08 09:47:22.000,DOANH THU DỊCH VỤ (chi tiết)
3,77257,S079,970,12386,STG_TB REGISTER DI ĐỘNG_THEO HẠ TẦNG (LK HỆ TH...,LINE,THANG,2021-10-28 16:34:52.000,4G Lũy kế
4,77258,S079,971,12386,STG_TB REGISTER DI ĐỘNG_THEO HẠ TẦNG (LK HỆ TH...,LINE,THANG,2021-10-28 16:34:52.000,3G Tăng giảm
...,...,...,...,...,...,...,...,...,...
57329,132568,TD,6003,23456,DANH SÁCH NHIỆM VỤ CHẬM TIẾN ĐỘ,TABLE_CONTENT,NaN,2023-05-25 09:06:41.000,Chậm tiến độ
57330,132353,TD,6002,23457,DANH SÁCH SẮP ĐẾN HẠN,TABLE_CONTENT,NaN,2023-05-25 09:12:43.000,Sắp đến hạn
57331,132354,TD,6003,23456,DANH SÁCH NHIỆM VỤ CHẬM TIẾN ĐỘ,TABLE_CONTENT,NaN,2023-05-25 09:06:41.000,Chậm tiến độ
57332,132355,TD,6002,23457,DANH SÁCH SẮP ĐẾN HẠN,TABLE_CONTENT,NaN,2023-05-25 09:12:43.000,Sắp đến hạn
57333,132356,TD,6003,23456,DANH SÁCH NHIỆM VỤ CHẬM TIẾN ĐỘ,TABLE_CONTENT,NaN,2023-05-25 09:06:41.000,Chậm tiến độ

In [18]:
# 185 dept_code
check_list = chart_dept['DEPT_CODE'].apply(lambda x: x.lower().strip())
list_dept_code = list(set(check_list))
len(list_dept_code)

167

In [27]:
list_dept_code[:5]

['t027', 'bdn', 'vtp', 'b240', 'idc']

In [23]:
def remove_donvi(title_chart):
    features = title_chart.split("_")
    if " " not in features[0] and features[0] not in ["company", 'info', 'test', 'rank', 'rada', 'table', 'tooltip', '21', 'dgsdf', 'khdn', 'dt-cp-ln', 'arpu', 'mou', 'dou']:
        output =  features[0]
        output2 = "_".join(features[1:])
    elif features[0] in ['tập đoàn', 'ban cntt', 'khối tỉnh/tp', 'công đoàn', 'viettel tỉnh/tp']:
        output = features[0]
        output2 = "_".join(features[1:])
    else:
        output = ""
        output2 = "_".join(features[0:])
    return output, output2
    

def remove_time(title_chart_rm_donvi):
    features = title_chart_rm_donvi.split("_")
    if len(features) == 1:
        features = "_".join(features)
        return features, ""
    output2 = ""
    output = deepcopy(features)
    for feature in features:
        for i in ['ngay', 'thang', 'nam', 'quy', 'ngày', 'tháng', 'năm', 'quý']:
            if i in feature:
                output2 = feature
                output.remove(feature)
                break
    
    output = "_".join(output)
    return output, output2

In [25]:
chart_dept_for_title = deepcopy(chart_dept)
chart_dept_for_title.drop(columns=['UPDATE_DATE'], inplace=True)
chart_dept_for_title = chart_dept_for_title.apply(lambda col: col.str.lower() if col.dtype!='int64' else col)
chart_dept_for_title['DONVI_FEATURE'] = chart_dept_for_title['TITLE_CHART'].apply(lambda x: remove_donvi(x)[0])
chart_dept_for_title['TITLE_CHART_RM_DONVI'] = chart_dept_for_title['TITLE_CHART'].apply(lambda x: remove_donvi(x)[1])
chart_dept_for_title['TIME_FEATURE'] = chart_dept_for_title['TITLE_CHART_RM_DONVI'].apply(lambda x: remove_time(x)[1])
chart_dept_for_title['TITLE_CHART_RM_DONVI_TIME'] = chart_dept_for_title['TITLE_CHART_RM_DONVI'].apply(lambda x: remove_time(x)[0])
chart_dept_for_title.drop(columns=['TITLE_CHART_RM_DONVI'], inplace=True)
chart_dept_for_title

,ID,DEPT_CODE,SERVICE_ID,CHART_ID,TITLE_CHART,TYPE_CHART,CYCTIME,SERVICE_NAME,DONVI_FEATURE,TIME_FEATURE,TITLE_CHART_RM_DONVI_TIME
0,77254,b281,143,16558,doanh thu dịch vụ tổng,mini,ngay,doanh thu dịch vụ (chi tiết),,,doanh thu dịch vụ tổng
1,77255,b281,143,16558,doanh thu dịch vụ tổng,title_mobile,ngay,doanh thu dịch vụ (chi tiết),,,doanh thu dịch vụ tổng
2,77256,b281,143,16558,doanh thu dịch vụ tổng,chart_rank_2,ngay,doanh thu dịch vụ (chi tiết),,,doanh thu dịch vụ tổng
3,77257,s079,970,12386,stg_tb register di động_theo hạ tầng (lk hệ th...,line,thang,4g lũy kế,stg,,tb register di động_theo hạ tầng (lk hệ thống)
4,77258,s079,971,12386,stg_tb register di động_theo hạ tầng (lk hệ th...,line,thang,3g tăng giảm,stg,,tb register di động_theo hạ tầng (lk hệ thống)
...,...,...,...,...,...,...,...,...,...,...,...
57329,132568,td,6003,23456,danh sách nhiệm vụ chậm tiến độ,table_content,NaN,chậm tiến độ,,,danh sách nhiệm vụ chậm tiến độ
57330,132353,td,6002,23457,danh sách sắp đến hạn,table_content,NaN,sắp đến hạn,,,danh sách sắp đến hạn
57331,132354,td,6003,23456,danh sách nhiệm vụ chậm tiến độ,table_content,NaN,chậm tiến độ,,,danh sách nhiệm vụ chậm tiến độ
57332,132355,td,6002,23457,danh sách sắp đến hạn,table_content,NaN,sắp đến hạn,,,danh sách sắp đến hạn
57333,132356,td,6003,23456,danh sách nhiệm vụ chậm tiến độ,table_content,NaN,chậm tiến độ,,,danh sách nhiệm vụ chậm tiến độ

In [33]:
# 185 dept_code
check_list = chart_dept_for_title['DEPT_CODE'].apply(lambda x: x.lower().strip())
list_dept_code = list(set(check_list))
len(list_dept_code)

167

In [58]:
list_dept_code

['',
 'tvh',
 'kha',
 'nan',
 'vtsport',
 'công đoàn',
 'idc',
 'bds',
 'hth',
 'nbh',
 'cto',
 'vtc',
 'vmc',
 'vht',
 'tvtk',
 'vte',
 'sla',
 'bnh',
 'kgg',
 'vtu',
 'khối tỉnh/tp',
 'vtnn',
 'vcm',
 'cbg',
 'unitel',
 'ctm',
 'hnm',
 'lan',
 'hgg',
 'vtnet',
 'xmcp',
 'vtcc',
 'ldg',
 'm3',
 'tgg',
 'viettel tỉnh/tp',
 'qnm',
 'ktm',
 'bitel',
 'hug',
 'pyn',
 'hyn',
 'qbh',
 'metfone',
 'dni',
 'dbn',
 'vdtc',
 'cmu',
 'vds',
 'nat',
 'tqg',
 'blu',
 'sxtb',
 'vtn',
 'ybi',
 'vcs',
 'dtp',
 'qni',
 'vtaca',
 'natcom',
 'hue',
 'tnn',
 'vam',
 'halotel',
 'vtx',
 'vtpost',
 'gli',
 'agg',
 'mytel',
 'ntn',
 'movitel',
 'hni',
 'bkn',
 'hpg',
 'hcm',
 'dcn',
 'vpc',
 'vttn',
 'dng',
 'xnk',
 'dlk',
 'stg',
 'lsn',
 'vcc',
 'vtk',
 'ban cntt',
 'telemor',
 'tbh',
 'vtg',
 'bdg',
 'dgd',
 'btn',
 'ndh',
 'dli',
 'tập đoàn',
 'pto',
 'qnh',
 'khcn',
 'tha',
 'vnc',
 'hdg',
 'gttd',
 'vtt',
 'vta',
 'bgg',
 'lumitel',
 'tnh',
 'lci',
 'bpc',
 'giangpth',
 'vtcommerce',
 'hbh',
 'lcu',
 'bte',
 'vts',
 'm1',
 'bdh',
 'vtm',
 'qti',
 'vlg']

In [37]:
list_dept_code[:5]

['', 'tvh', 'kha', 'nan', 'vtsport']

In [35]:
# 185 dept_code
check_list = chart_dept_for_title['DONVI_FEATURE'].apply(lambda x: x.lower().strip())
list_dept_code = list(set(check_list))
len(list_dept_code)

120

In [38]:
list_dept_code[:5]

['', 'tvh', 'kha', 'nan', 'vtsport']